# k8s/secrets.example.yaml
# NE PAS COMMITTER LE FICHIER AVEC LES VRAIES VALEURS
apiVersion: v1
kind: Secret
metadata:
  name: demystops-secrets
  namespace: demystops
type: Opaque
stringData:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "votre-email@gmail.com"
  SMTP_PASS: "votre-mot-de-passe-d-application"
  SMTP_SECURE: "false"
