apiVersion: v1
kind: Service
metadata:
  name: demystops-service
  namespace: demystops
spec:
  selector:
    app: demystops
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort